### ISSUE TITLE
App opens but does nothing.

### ISSUE THREAD

**Issue by RabidPope** [GraySquyd/BG3-Better-Camera#1]
There is no error. It just does not set anything when I click on set. 
Disabled antivirus. Rechecked integrity of game files. EXE has a different version?
![image](https://github.com/GraySquyd/BG3-Better-Camera/assets/55444317/6a9a7fc9-060b-4cc3-bc60-3ba95907564d)

**Comment by Squydy** [comment]
Yes they updated the game. I have pushed an update to fix this

**Comment by RabidPope** [comment]
Ah ok. Thanx. Thought it was a problem on my end with steam. Strange it didnt give an error.

**Comment by Squydy** [comment]
> Ah ok. Thanx. Thought it was a problem on my end with steam. Strange it didnt give an error.

It's still *technically* working, just not correctly, so there's no error for that. I added a version checker to help clear up confusion in the future.
