### ISSUE TITLE
Seems to not be working on the GOG version

### ISSUE THREAD

**Issue by Azzurite** [GraySquyd/BG3-Better-Camera#2]
My friends I play with play on Steam and everything works fine, but for me the app just does literally nothing.

Can I do anything to help make this work for GOG?

**Comment by BlackburnUTG** [comment]
steam version here. I launched the game and corresponding bc exe. BG3.BetterCamera.v1.4.1.VK
I can change values but cant see any result ingame

**Comment by Squydy** [comment]
> My friends I play with play on Steam and everything works fine, but for me the app just does literally nothing.
> 
> Can I do anything to help make this work for GOG?

Yes if you can give me your discord information I can add you and walk you through making it compatible. I would do it myself but I don't want to buy a game twice.

> steam version here. I launched the game and corresponding bc exe. BG3.BetterCamera.v1.4.1.VK I can change values but cant see any result ingame

After you type in a value in the box you need to hit the set button. I recommend carefully rereading the instructions and if that doesn't work there is a paragraph about bug reporting. I can't really trouble shoot without more information. Also please open up your own issue for separate issues.

**Comment by KunAguero9320** [comment]
"I can add you and walk you through making it compatible"
If you plan on keeping BC2 up to date (I notice you redirect to BG3Cam now) I'd be open to doing this. Weathers#3532
