### ISSUE TITLE
Breaks WASD/Thumbstick camera

### ISSUE THREAD

**Issue by KunAguero9320** [GraySquyd/BG3-Better-Camera#3]
Latest version (1.4.1) won't allow movement of the cam.

**Comment by Squydy** [comment]
You probably just set the camera distance to zero. This is how far you are allowed to move the camera from the character with WASD, when set to zero you cannot move it at all. I don't have any problem moving the camera and doesn't seem to be a wide spread issue, so I'm going to go with this.

**Comment by KunAguero9320** [comment]
I didn't change the cam distance, I only changed the FOVs and Angles, and the hotkey bindings (using 6,7, ctrl+6, crtl+7, and 0,9 and ctrl+0, ctrl+9) for those.
Perhaps I accidentally did so. It is working now anyway.
Thanks for the tool btw, it makes the game even better.

**Comment by Squydy** [comment]
> I didn't change the cam distance, I only changed the FOVs and Angles, and the hotkey bindings (using 6,7, ctrl+6, crtl+7, and 0,9 and ctrl+0, ctrl+9) for those. Perhaps I accidentally did so. It is working now anyway. Thanks for the tool btw, it makes the game even better.

I think sometimes people do it accidentally when typing in values with the numpad since 1 and 2 are bound by default to it. Either that or it glitches. Simple fix either way. Glad it's working now.
